require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Allow longer lines in specs
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Don't require class/module documentation
Style/Documentation:
  Enabled: false

# Allow longer blocks in specs and routes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'

# Don't require frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow more than 10 lines in methods for controllers
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'

# Allow longer classes
Metrics/ClassLength:
  Max: 150

# RSpec specific
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4